// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pkg/module/id/pb/id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateSnowflakeIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateSnowflakeIdReq) Reset() {
	*x = GenerateSnowflakeIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_module_id_pb_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSnowflakeIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSnowflakeIdReq) ProtoMessage() {}

func (x *GenerateSnowflakeIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_module_id_pb_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSnowflakeIdReq.ProtoReflect.Descriptor instead.
func (*GenerateSnowflakeIdReq) Descriptor() ([]byte, []int) {
	return file_pkg_module_id_pb_id_proto_rawDescGZIP(), []int{0}
}

type GenerateSnowflakeIdRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    int64  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GenerateSnowflakeIdRsp) Reset() {
	*x = GenerateSnowflakeIdRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_module_id_pb_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSnowflakeIdRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSnowflakeIdRsp) ProtoMessage() {}

func (x *GenerateSnowflakeIdRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_module_id_pb_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSnowflakeIdRsp.ProtoReflect.Descriptor instead.
func (*GenerateSnowflakeIdRsp) Descriptor() ([]byte, []int) {
	return file_pkg_module_id_pb_id_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateSnowflakeIdRsp) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateSnowflakeIdRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateSnowflakeIdRsp) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_pkg_module_id_pb_id_proto protoreflect.FileDescriptor

var file_pkg_module_id_pb_id_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x69, 0x64, 0x2f,
	0x70, 0x62, 0x2f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x69, 0x64, 0x22,
	0x18, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x6f, 0x77, 0x66,
	0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x22, 0x5a, 0x0a, 0x16, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64,
	0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x5c, 0x0a, 0x09, 0x49, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x6e,
	0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x69, 0x64, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x69, 0x64, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x67, 0x73, 0x6c, 0x69, 0x66, 0x65, 0x2f, 0x74, 0x6f, 0x6f, 0x6c,
	0x62, 0x6f, 0x78, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x69,
	0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_module_id_pb_id_proto_rawDescOnce sync.Once
	file_pkg_module_id_pb_id_proto_rawDescData = file_pkg_module_id_pb_id_proto_rawDesc
)

func file_pkg_module_id_pb_id_proto_rawDescGZIP() []byte {
	file_pkg_module_id_pb_id_proto_rawDescOnce.Do(func() {
		file_pkg_module_id_pb_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_module_id_pb_id_proto_rawDescData)
	})
	return file_pkg_module_id_pb_id_proto_rawDescData
}

var file_pkg_module_id_pb_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_module_id_pb_id_proto_goTypes = []interface{}{
	(*GenerateSnowflakeIdReq)(nil), // 0: id.GenerateSnowflakeIdReq
	(*GenerateSnowflakeIdRsp)(nil), // 1: id.GenerateSnowflakeIdRsp
}
var file_pkg_module_id_pb_id_proto_depIdxs = []int32{
	0, // 0: id.IdService.GenerateSnowflakeId:input_type -> id.GenerateSnowflakeIdReq
	1, // 1: id.IdService.GenerateSnowflakeId:output_type -> id.GenerateSnowflakeIdRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_module_id_pb_id_proto_init() }
func file_pkg_module_id_pb_id_proto_init() {
	if File_pkg_module_id_pb_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_module_id_pb_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSnowflakeIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_module_id_pb_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSnowflakeIdRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_module_id_pb_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_module_id_pb_id_proto_goTypes,
		DependencyIndexes: file_pkg_module_id_pb_id_proto_depIdxs,
		MessageInfos:      file_pkg_module_id_pb_id_proto_msgTypes,
	}.Build()
	File_pkg_module_id_pb_id_proto = out.File
	file_pkg_module_id_pb_id_proto_rawDesc = nil
	file_pkg_module_id_pb_id_proto_goTypes = nil
	file_pkg_module_id_pb_id_proto_depIdxs = nil
}
